### ISSUE TITLE
Getting 404 Errors when opening a Tiddly page in Google Drive.

### ISSUE THREAD

**Issue by hanstar17** [tiddlydrive/tiddlydrive.github.io#6]
Hi, I really appreciate the web application you made. I have been enjoying it so much.

Today, I was accessing the page as normal through Tiddly Drive and getting 404 Web error. I think this is happening for all as you can observe in the Chrome extension's support tab: https://chrome.google.com/webstore/detail/tiddly-drive/oaphhjhbbabdjnpjpiliepphpmnioolo/support?utm_source=www.crx4chrome.com

Thanks.

**Comment by edwinsc** [comment]
I also thank you for your efforts, and I'm having the same problem.

**Comment by LordRatte** [comment]
Hi, guys.

Unfortunately this error is with the hosting platform I'm using. They have
dated the fix for the 20th of February. I will let you know as soon as it
has been fixed.

**Comment by hanstar17** [comment]
Thank you very much.

**Comment by bjarkekronborg** [comment]
To second the other people. I greatly enjoy the integration with Google Drive. And just wanted to give a heads up that I am still experiencing the 404 error. Keep up the good work and thank you for making TW better. 
Cheers,

**Comment by LordRatte** [comment]
Hi, everyone.

I'm still waiting for my host to fix their domain issue. I will let you
know when it is fixed. Sorry for the inconvenience!

**Comment by LordRatte** [comment]
Ok, it's all fixed now. Thank you everyone for your patience.

**Comment by edwinsc** [comment]
Thank you for the app.

If you want to explain how your app work and what are the single points of
failure, I can check if it is possible for me to offer a backup path to
avoid such bottlenecks.

Edwin Cordeiro

**Comment by LordRatte** [comment]
@edwinsc I doubt this specific issue will happen again but if you want you can pop me an email at joshua@lordratte.info

**Comment by hanstar17** [comment]
Thank you so much, I appreciate it!
